Iter1
m1khal3v/gophermart-loyalty-service pull request #1
Opened 2024-08-03 21:46 UTC by m1khal3v

2024-08-07 13:37 UTC, tmvrus requested changes
Есть над чем подумать

2024-08-07 13:37 UTC, tmvrus commented on cmd/gophermart/main.go
> +	container, err := container.New(config)
Из названия компонента ничего не следует, а из использования следует что он отвечает практически за все, рекомендую пересмотреть подход и выделить для каждой области/ответственности свой компонент.

2024-08-07 13:37 UTC, tmvrus commented on cmd/gophermart/main.go
> +	<-serverCtx.Done()
к этому блоку пара вопросов:
- зачем понадобилось два разных контекста? если нужно дождаться завершения всех горутин/фоновых задач то используется WaitGroup, других применений двум разным контекста из кода не очевидно
- по какой причине при ошибка server.Start вызывается Fatal но при всех остальных -Error, использование Fatal вообще лишает смысла контексты, поскольку приложение завершается аварийно
- как произойдет остановка приложения если ошибок не будет? почему что бы это понять нужно изучить server а не контейнер?

2024-08-07 13:37 UTC, tmvrus commented on pkg/client/client.go
> +type ErrUnexpectedStatus struct {
ошибка лежит в файле client.go
это странно

2024-08-07 13:37 UTC, tmvrus commented on pkg/client/client.go
> +	var result *resty.Response = nil
можно короче var result *resty.Response

2024-08-07 13:37 UTC, tmvrus commented on internal/controller/order/register.go
> +		controller.WriteJSONErrorResponse(http.StatusBadRequest, writer, "invalid Content-Type", nil)
return?

2024-08-07 13:37 UTC, tmvrus commented on internal/accrual/client/client.go
> +			return ErrInternalServerError
мапить  статус в кастомную ошибку имеет смысл в том случае, если с этой ошибкой дальше какая-то логика связана, какая логика связана с ErrInternalServerError?
тоже самое касается ErrOrderNotFound

2024-08-07 13:37 UTC, tmvrus commented on pkg/retry/retry.go
> +	return err
синтаксически всегда возвращается ошибка, лучше все такие писать return nil если ошибки не было, так будет читабельней

2024-08-07 13:37 UTC, tmvrus commented on internal/accrual/task/task.go
> +}
а почему нельзя сделать так что бы Post возвращал либо item либо nil и никогда список?
я могу ошибаться, но общеупотребимая семантика Pop/Push как раз подразумевает что мы работаем с 1 элементом

2024-08-07 13:37 UTC, tmvrus commented on internal/router/router.go
> +				if appEnv == "prod" {
это что за костыль?

2024-08-07 13:37 UTC, tmvrus commented on internal/accrual/client/client.go
> +	return result.Result().(*responses.Accrual), nil
ЗАчем такие сложности с type casting, да еще небезопасным способом?
выше есть SetResult он разве не для этого нужен?

2024-08-07 13:37 UTC, tmvrus commented on internal/accrual/processor/retriever.go
> +	client  *client.Client
читая код хотелось бы понимать чего именно это клиент

2024-08-07 13:37 UTC, tmvrus commented on internal/accrual/processor/retriever.go
> +				}
Это можно переписать явным образом
```
x := client.ErrTooManyRequests{}
if errors.As(err, &x) {
    retryAfterChannel <- x
}
```

2024-08-07 13:37 UTC, tmvrus commented on internal/accrual/client/client.go
> +			retryAfter, err := strconv.ParseUint(result.Header().Get("Retry-After"), 10, 64)
там может быть непросто число
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After
а еще я бы рекомендовал подстраховаться и сделать дефолтную задержку если сервер не сообщил ее в ответе потому как "my be included" еще ничего не гарантирует
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

2024-08-07 13:37 UTC, tmvrus commented on internal/accrual/processor/retriever.go
> +			continue
ситуация:  `concurrency=10` запустили 10 горутин. все вернули ошибку `ErrTooManyRequests` 9 заблокироввались на запись в retryAfterChannel и держат свои семафоры, одна смогла записать, освободила семафор.
- дождались `time.Sleep(err.RetryAfterTime.Sub(now))`, 9 все все еще заблокированы и держат свой семафор
- начали вычитывать остальные из retryAfterChannel каждый раз проверяя now.Before при этом "возвращая" один семафор за раз
Учитывая что мы не знаем, какое время нам вернет сервер, канал не выглядит надежным решением.

2024-08-07 13:37 UTC, tmvrus commented on internal/accrual/processor/retriever.go
> +		}
если 1 из многих не сможет взять семафор, ф-я перестанет работать, выполнится `defer close(retryAfterChannel)`
и все остальные, начнут писать в закрытый канал, будет паника

канал не выглядит надежным решенеим

2024-08-08 11:08 UTC, m1khal3v commented on cmd/gophermart/main.go
> +	container, err := container.New(config)
тут дело в том что в разных областях местами используются одни и те же сервисы, т.е они должны быть singletone, а этот контейнер исполняет роль DI и возвращает контейнер с 3мя основными сервисами внутрь которых уже все прокинуто как полагается. но я подумаю как тут лучше переделать

2024-08-08 11:10 UTC, m1khal3v commented on cmd/gophermart/main.go
> +	<-serverCtx.Done()
тут тоже подумаю как лучше переделать. но суть такая что если сервер останавливается то он останавливает процессоры. если останавливаются процессоры, то они останавливают сервер. с Fatalom косякнул

2024-08-08 11:11 UTC, m1khal3v commented on pkg/client/client.go
> +type ErrUnexpectedStatus struct {
их лучше выносить в отдельный файл рядом?

2024-08-08 11:18 UTC, m1khal3v commented on internal/accrual/client/client.go
> +			return ErrInternalServerError
когда пишу клиент часто закладываю в него все варианты ответа "на потом", т.к не хочется часто возвращаться к документации, которая может со временем вообще пропасть, переместится и т.д. к тому же каждая конкретная ошибка здесь передается выше уровнем где попадает в логгер warn, можно конечно обойтись общей ошибкой под код, который мы не обрабатываем, но отдельная ошибка информативнее

2024-08-08 11:19 UTC, m1khal3v commented on internal/accrual/task/task.go
> +}
тут я просто скопипастил решение с предыдущего проекта и пока не оптимизировал его под текущее (а там удобнее было забирать сразу батч). поправлю

2024-08-08 11:20 UTC, m1khal3v commented on internal/router/router.go
> +				if appEnv == "prod" {
оберег от падающих автотестов Яндекса, ничего умнее не придумал)

2024-08-08 11:24 UTC, m1khal3v commented on internal/accrual/client/client.go
> +	return result.Result().(*responses.Accrual), nil
Там к сожалению не используются дженерики и наверно в Go так пока не получится в принципе. SetResult сетит объект на который будет мапится json/xml результат, Result возращает any а т.к моя функция должна вернуть конкретный класс то приходится кастить. в офф документации resty тоже предлагается делать именно так https://pkg.go.dev/github.com/go-resty/resty/v2#Request.SetResult

2024-08-08 11:25 UTC, m1khal3v commented on internal/accrual/client/client.go
> +			retryAfter, err := strconv.ParseUint(result.Header().Get("Retry-After"), 10, 64)
подумаю над этим

2024-08-08 11:31 UTC, m1khal3v commented on internal/accrual/processor/retriever.go
> +			continue
тут не совсем так. если 10 вернули ошибку то мы отпускаем все 10 семафоров и возращаемся к родительской горутине которая поспит один раз и continue к циклу for, дальше мы прочитаем 9 раз сообщение время в котором уже будет тухлое, спать не будем, каждый раз возвращаясь к началу for. когда сообщения кончатся мы пройдем через default к получению семафора, т.к все самафоры будут свободны то мы опять запустим 10 горутин. 

но к этому блоку у меня у самого есть ряд вопросов которые я оставил на 2ю итерацию

2024-08-08 11:35 UTC, m1khal3v commented on internal/accrual/processor/retriever.go
> +		}
тут не получится так что один из немногих не сможет взять семафор. берет семафор основная горутина, кстати в предыдущем проекте я эту правку тоже откатил до такого же решения, потому что если семафор брать внутри горутины то мы запустим неограниченное количество горутин, создание дочерней горутины должно контроллироваться за счет семафора из родительской горутины, чтобы так не произошло. 

а вот по поводу пограничного кейса на счет паники это да, такая вероятность есть, хоть и крайне мала, надо будет проработать

2024-08-08 13:20 UTC, tmvrus commented on pkg/client/client.go
> +type ErrUnexpectedStatus struct {
я бы положил рядом в errors.go

2024-08-09 17:32 UTC, m1khal3v commented
@tmvrus [правки отдельной ссылкой](https://github.com/m1khal3v/gophermart-loyalty-service/pull/1/commits/8dedbf076dae8b30fa31846dcf639ccc252cc9d2). тесты пока не писал, их набросаю когда основной код окнем

2024-08-10 13:47 UTC, m1khal3v commented
@tmvrus [правки отдельной ссылкой](https://github.com/m1khal3v/gophermart-loyalty-service/pull/1/files/808b4f4763915ef303fdd07332b12d2079623839..0df8a134a9eb7dd8e8936808c531e025afe5eb65). тесты пока не писал, их набросаю когда основной код окнем

2024-08-13 12:46 UTC, tmvrus commented
> @tmvrus [правки отдельной ссылкой](https://github.com/m1khal3v/gophermart-loyalty-service/pull/1/files/808b4f4763915ef303fdd07332b12d2079623839..70f30399e7ae0928c23184028736ad70ce2647dc). тесты пока не писал, их набросаю когда основной код окнем

так не получится, определяйся либо проект готов(тогда в нем должны таки быть тесты), либо нет, тогда заканчивай.

2024-08-20 13:50 UTC, tmvrus approved these changes
Хорошая работа.

2024-08-20 13:50 UTC, tmvrus commented on internal/middleware/recover.go
> +				}
вот это очень похоже на попытку использовать панику как исключения, но это все же не одно и тоже.

2024-08-20 15:08 UTC, merged